env:
  - CUCUMBER_TESTS=importing
  - CUCUMBER_TESTS=challenges
  - CUCUMBER_TESTS=collections
  - CUCUMBER_TESTS=users
  - CUCUMBER_TESTS=works
  - CUCUMBER_TESTS=tags_and_wrangling
  - CUCUMBER_TESTS=other
  - RSPEC_TESTS=spec
rvm:
  - "1.9.3"
services:
  - elasticsearch
  - redis-server
  - memcache
script:
  - bundle exec rake db:create:all --trace
  - bundle exec rake db:schema:load --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec cucumber -f progress -r features features/$CUCUMBER_TESTS
  - bundle exec rspec $RSPEC_TESTS
before_script:
  - mysql -e 'create database otwarchive_test;'
  - cp config/database.travis.yml config/database.yml
  - cp config/newrelic.example config/newrelic.yml
  - cp config/redis-cucumber.conf.example config/redis-cucumber.conf
  - cp config/redis.travis.example config/redis.yml
notifications:
  email:
    recipients:
      - otw-coders@transformativeworks.org
    on_success: change
    on_failure: always
  irc:
   channels:
     - "irc.freenode.org#otw-dev"
   on_success: always
   on_failure: always
