language: ruby
env:
  - TEST_GROUP="./script/check_syntax"
rvm:
  - "1.9.3"
services:
  - elasticsearch
  - redis-server
  - memcached
script:
  - bundle exec rake db:create:all --trace
  - bundle exec rake db:schema:load --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec $TEST_GROUP
before_script:
  - bash script/travis_configure.sh
  - bash script/travis_elasticsearch_upgrade.sh
after_script:
  - bundle exec rake coveralls:push
notifications:
  email:
    recipients:
      - otw-coders@transformativeworks.org
    on_success: change
    on_failure: always
  irc:
   channels:
     - "irc.freenode.org#otw-dev"
   on_success: change
   on_failure: always
