env:
  - TEST_GROUP=bundle exec cucumber -f progress features/importing
  - TEST_GROUP=bundle exec cucumber -f progress features/gift_exchanges
  - TEST_GROUP=bundle exec cucumber -f progress features/prompt_memes
  - TEST_GROUP=bundle exec cucumber -f progress features/collections
  - TEST_GROUP=bundle exec cucumber -f progress features/users
  - TEST_GROUP=bundle exec cucumber -f progress features/works
  - TEST_GROUP=bundle exec cucumber -f progress features/tags_and_wrangling
  - TEST_GROUP=bundle exec cucumber -f progress features/other
  - TEST_GROUP=bundle exec rspec spec
rvm:
  - "1.9.3"
services:
  - elasticsearch
  - redis-server
  - memcache
script:
  - bundle exec rake db:create:all --trace
  - bundle exec rake db:schema:load --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - $TEST_GROUP
before_script:
  - mysql -e 'create database otwarchive_test;'
  - cp config/database.travis.yml config/database.yml
  - cp config/newrelic.example config/newrelic.yml
  - cp config/redis-cucumber.conf.example config/redis-cucumber.conf
  - cp config/redis.travis.example config/redis.yml
notifications:
  email:
    recipients:
      - otw-coders@transformativeworks.org
    on_success: change
    on_failure: always
  irc:
   channels:
     - "irc.freenode.org#otw-dev"
   on_success: always
   on_failure: always
