language: ruby
env:
  - TEST_GROUP="rspec spec/models/work_search_spec.rb"
rvm:
  - "1.9.3"
services:
  - elasticsearch
  - redis-server
  - memcached
script:
  - bundle exec rake db:create:all --trace
  - bundle exec rake db:schema:load --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec $TEST_GROUP
before_script:
  - mysql -e 'create database otwarchive_test;'
  - cp config/database.travis.yml config/database.yml
  - cp config/newrelic.example config/newrelic.yml
  - cp config/redis-cucumber.conf.example config/redis-cucumber.conf
  - cp config/redis.travis.example config/redis.yml
  - curl -L https://gist.githubusercontent.com/scottsds/8fda6f6fbc66d3a2315e/raw/1d4b990f7922e388d6d7563b9e5cda7c97af18a7/gistfile1.sh | bash
notifications:
  email:
    recipients:
      - otw-coders@transformativeworks.org
    on_success: change
    on_failure: always
  irc:
   channels:
     - "irc.freenode.org#otw-dev"
   on_success: always
   on_failure: always
